Hackathon/Hackathon/Controllers/NalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hackathon.DomainModel;
using Hackathon.Models;

namespace Hackathon.Controllers
{   
    public class NalsController : Controller
    {
		private readonly INalRepository nalRepository;

		// If you are using Dependency Injection, you can delete the following constructor
        public NalsController() : this(new nalRepository())
        {
        }

        public NalsController(INalRepository nalRepository)
        {
			this.nalRepository = nalRepository;
        }

        //
        // GET: /nals/

        public ViewResult Index()
        {
            return View(nalRepository.All);
        }

        //
        // GET: /nals/Details/5

        public ViewResult Details(int id)
        {
            return View(nalRepository.Find(id));
        }
        [HttpGet]
        public ViewResult Search()
        {
            return View();
        }
        [HttpPost]
        public ViewResult Search(string owner1 = "", string m_addr_1 = "")
        {
            return View("SearchResult", nalRepository.Search(owner1, m_addr_1));
        }

        //
        // GET: /nals/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /nals/Create

        [HttpPost]
        public ActionResult Create(nal nal)
        {
            if (ModelState.IsValid) {
                nalRepository.InsertOrUpdate(nal);
                nalRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }
        
        //
        // GET: /nals/Edit/5
 
        public ActionResult Edit(int id)
        {
             return View(nalRepository.Find(id));
        }

        //
        // POST: /nals/Edit/5

        [HttpPost]
        public ActionResult Edit(nal nal)
        {
            if (ModelState.IsValid) {
                nalRepository.InsertOrUpdate(nal);
                nalRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }

        //
        // GET: /nals/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(nalRepository.Find(id));
        }

        //
        // POST: /nals/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            nalRepository.Delete(id);
            nalRepository.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                nalRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hackathon/Hackathon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @*<meta name="viewport" content="width=device-width" />*@
    <!--The viewport meta tag is used to improve the presentation and behavior of the samples 
      on iOS devices-->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,user-scalable=no">

    <link rel="stylesheet" href="http://serverapi.arcgisonline.com/jsapi/arcgis/3.4/js/dojo/dijit/themes/claro/claro.css">
    <link rel="stylesheet" href="http://serverapi.arcgisonline.com/jsapi/arcgis/3.4/js/esri/css/esri.css">
        <script src="http://localhost:18051/Scripts/jquery-1.9.1.js" type="text/javascript"></script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Hack A thon", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Search", "Search", "Nals")</li>
                            <li>@Html.ActionLink("Parcels", "Index", "Nals")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Hack A Thon 2013</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Hackathon/Hackathon/Views/Shared/_Layout.mobile.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
               mobile
                <div class="float-right">
                    
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Sales", "Search", "Nals")</li>
                            <li>@Html.ActionLink("Nal", "Index", "Nals")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Hack A Thon 2013</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>